export default {
  GET_CHARACTER_PENDING: "GET_CHARACTER_PENDING",
  GET_CHARACTER_SUCCESS: "GET_CHARACTER_SUCCESS",
  GET_CHARACTER_FAIL: "GET_CHARACTER_FAIL",

  GET_ALL_CHARACTERS_PENDING: "GET_ALL_CHARACTERS_PENDING",
  GET_ALL_CHARACTERS_SUCCESS: "GET_ALL_CHARACTERS_SUCCESS",
  GET_ALL_CHARACTERS_FAIL: "GET_ALL_CHARACTERS_FAIL",

  GET_EPISODES_PENDING: "GET_EPISODES_PENDING",
  GET_EPISODES_SUCCESS: "GET_EPISODES_SUCCESS",
  GET_EPISODES_FAIL: "GET_EPISODES_FAIL",

  GET_ALL_FAVORITES_PENDING: "GET_ALL_FAVORITES_PENDING",
  GET_ALL_FAVORITES_SUCCESS: "GET_ALL_FAVORITES_SUCCESS",
  GET_ALL_FAVORITES_FAIL: "GET_ALL_FAVORITES_FAIL",

  ADD_FAVORITE_PENDING: "ADD_FAVORITE_PENDING",
  ADD_FAVORITE_SUCCESS: "ADD_FAVORITE_SUCCESS",
  ADD_FAVORITE_FAIL: "ADD_FAVORITE_FAIL",

  UPDATE_FAVORITE_PENDING: "UPDATE_FAVORITE_PENDING",
  UPDATE_FAVORITE_SUCCESS: "UPDATE_FAVORITE_SUCCESS",
  UPDATE_FAVORITE_FAIL: "UPDATE_FAVORITE_FAIL",

  DELETE_FAVORITE_PENDING: "DELETE_FAVORITE_PENDING",
  DELETE_FAVORITE_SUCCESS: "DELETE_FAVORITE_SUCCESS",
  DELETE_FAVORITE_FAIL: "DELETE_FAVORITE_FAIL",

  TOGGLE_FAVORITE: "TOGGLE_FAVORITE",
};
