export default {
  GET_CHARACTER_PENDING: "GET_CHARACTER_PENDING",
  GET_CHARACTER_SUCCESS: "GET_CHARACTER_SUCCESS",
  GET_CHARACTER_FAIL: "GET_CHARACTER_FAIL",

  GET_ALL_CHARACTERS_PENDING: "GET_ALL_CHARACTERS_PENDING",
  GET_ALL_CHARACTERS_SUCCESS: "GET_ALL_CHARACTERS_SUCCESS",
  GET_ALL_CHARACTERS_FAIL: "GET_ALL_CHARACTERS_FAIL",

  GET_EPISODES_PENDING: "GET_EPISODES_PENDING",
  GET_EPISODES_SUCCESS: "GET_EPISODES_SUCCESS",
  GET_EPISODES_FAIL: "GET_EPISODES_FAIL",
};
